# Generated by Django 3.1.2 on 2020-10-11 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('mac_no', models.CharField(default='', max_length=255)),
                ('bach_no', models.CharField(default='', max_length=255)),
                ('serial_numbe', models.CharField(default='', max_length=255)),
                ('conclusion', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Board',
            },
        ),
        migrations.CreateModel(
            name='board_faults_categories',
            fields=[
                ('board_faults_categories_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_issue', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Board Type Categories',
                'verbose_name_plural': 'Board Type Categories',
            },
        ),
        migrations.CreateModel(
            name='board_type',
            fields=[
                ('board_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Board Type',
                'verbose_name_plural': 'Board Types',
            },
        ),
        migrations.CreateModel(
            name='repair_record',
            fields=[
                ('board_repair_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('open_date', models.DateField()),
                ('closed_date', models.DateField()),
                ('issue_no', models.CharField(max_length=200)),
                ('fault_local_agent', models.TextField()),
                ('suspect_fault_after_checkup', models.TextField()),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp.board')),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp.board_faults_categories')),
            ],
            options={
                'verbose_name': 'Repair Record',
                'verbose_name_plural': 'Repair Records',
            },
        ),
        migrations.CreateModel(
            name='repair_record_progress',
            fields=[
                ('board_repair_record_progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('staff', models.CharField(max_length=255)),
                ('workdone', models.TextField()),
                ('repair_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp.repair_record')),
            ],
            options={
                'verbose_name': 'Repair records progess',
                'verbose_name_plural': 'Repair records progess',
            },
        ),
        migrations.AddField(
            model_name='board_faults_categories',
            name='board_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp.board_type'),
        ),
        migrations.AddField(
            model_name='board',
            name='board_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp.board_type'),
        ),
    ]
