# Generated by Django 3.1.2 on 2020-10-12 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mp', '0002_auto_20201011_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair_record',
            name='fault_local_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
