# Generated by Django 3.1.2 on 2020-10-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0003_auto_20201012_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repair_record',
            old_name='board_id',
            new_name='board_serial_number',
        ),
        migrations.RenameField(
            model_name='repair_record',
            old_name='board_repair_record_id',
            new_name='repair_record_id',
        ),
        migrations.AlterField(
            model_name='repair_record',
            name='fault_local_agent',
            field=models.CharField(max_length=200),
        ),
    ]
