# Generated by Django 3.1.2 on 2020-10-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0004_auto_20201017_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repair_record',
            name='issue_id',
        ),
        migrations.AlterField(
            model_name='repair_record',
            name='suspect_fault_after_checkup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp.board_faults_categories'),
        ),
    ]
