# Generated by Django 3.1.2 on 2020-10-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0005_auto_20201017_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_type',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
