# Generated by Django 3.1.2 on 2020-10-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0006_auto_20201025_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='bach_no',
            new_name='batch_no',
        ),
    ]
