# Generated by Django 3.1.2 on 2020-10-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0007_auto_20201026_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='serial_number',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='board_faults_categories',
            name='board_issue',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
