# Generated by Django 3.1.2 on 2020-10-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0008_auto_20201027_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_faults_categories',
            name='board_issue',
            field=models.CharField(max_length=255),
        ),
    ]
