# Generated by Django 3.1.2 on 2020-11-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0009_auto_20201030_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repair_record',
            name='suspect_fault_after_checkup',
        ),
        migrations.AddField(
            model_name='repair_record',
            name='suspect_fault_after_checkup',
            field=models.ManyToManyField(to='mp.board_faults_categories'),
        ),
    ]
