# Generated by Django 3.1.2 on 2020-11-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0011_auto_20201117_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('opt0', 'Pass'), ('opt1', 'Fail'), ('opt1', 'in progress')], max_length=200, verbose_name='status'),
        ),
    ]
