# Generated by Django 3.1.2 on 2020-12-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0012_auto_20201123_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('In Progress', 'In Progress')], max_length=200, verbose_name='status'),
        ),
    ]
