# Generated by Django 3.1.2 on 2021-01-15 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0016_auto_20210115_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='mac_no',
            field=models.CharField(default='', max_length=17, validators=[django.core.validators.RegexValidator('^([A-Z]{2}[:-]){5}([0-9A-Fa-f]{2})$')]),
        ),
        migrations.AlterField(
            model_name='board',
            name='serial_number',
            field=models.CharField(default='', help_text='12 number only', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')]),
        ),
    ]
