# Generated by Django 3.1.2 on 2021-01-15 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0017_auto_20210115_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='mac_no',
            field=models.CharField(default='', max_length=17, validators=[django.core.validators.RegexValidator('^((([A-F][A-F]+[:-]){5}|([a-fA-F0-9][a-fA-F0-9]+[:]){5})([a-fA-F0-9][a-fA-F0-9])$)')]),
        ),
    ]
